---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  # Each SITE_ID is a different zone
  topology.kubernetes.io/zone: ran-du-bangalore-server-profile-du-dell-r640-00

commonAnnotations:
 #argocd.argoproj.io/sync-wave: "20"
 argocd.argoproj.io/sync-options: Prune=false
 argocd.argoproj.io/compare-options: IgnoreExtraneous
# Apps of Apps
resources:
  - 40-aiops-cluster-bangalore-dell-du.yaml
  - 50-aiops-cluster-bangalore-dell-du-00-pre.yaml
  - 60-aiops-cluster-bangalore-dell-du-01-post.yaml
  - 70-aiops-cluster-bangalore-dell-du-02-configs.yaml
  - 80-aiops-cluster-bangalore-dell-du-03-n3k.yaml
  - 90-aiops-cluster-bangalore-dell-du-n3k-sriov.yaml
  - 110-aiops-cluster-bangalore-dell-du-sriovfec-clusterconfig.yaml
  - 120-aiops-cluster-bangalore-dell-du-04-timingmgr.yaml
  - 100-aiops-cluster-bangalore-dell-du-n3k-cluster.yaml
