---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ./bangalore/dell/du

# Apps of Apps
resources:

  # - 10-gemini.yaml
  - 10-aiops-cluster.yaml
  - 20-aiops-cluster-sriovconfig.yaml
  - 30-aiops-cluster-ptpconfig.yaml