---
apiVersion: config.openshift.io/v1
kind: Image
metadata:
  annotations:
    release.openshift.io/create-only: "true"
  name: cluster
spec:
  additionalTrustedCA:
    name: quay-vranmgmt1-config
  registrySources:
    insecureRegistries:      
    - mirror-registry-vranmgmt1.fyre.ibm.com:5000
